apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Upstream release, vendored verbatim:
  # https://github.com/buildpacks-community/kpack/releases/download/v0.18.0/release-0.18.0.yaml
  - release.yaml
  - builder.yaml
