apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../kinit.d/issuers
  - ../../kinit.d/awspca-issuers # Use AWS Private CA
  - ../../kinit.d/awslb # For services that need direct NLB IP Source
  - ../../kinit.d/nginx-ingress-aws # For other services (internal and external)
  - ../../kinit.d/externaldns # register services outside