kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: dummy-go
  namespace: dummy-go
spec:
  rules:
    - host: dummy-go.staging
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: dummy-go-service
                port:
                  number: 8080