apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: awspca
  namespace: cert-manager
spec:
  interval: 24h
  url: https://cert-manager.github.io/aws-privateca-issuer
---