apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-iugu-cert
  namespace: cert-manager
spec:
  commonName: example.iugu
  dnsNames:
    - example.iugu
  secretName: test-iugu-cert-tls
  issuerRef:
    name: iugu-cluster-pca
    kind: AWSPCAClusterIssuer
    group: awspca.cert-manager.io
