apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: nginx
spec:
  values:
    controller:
      $patch: replace
      ingressClassByName: true
      ingressClass: nginx
      replicaCount: 2
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
        controllerValue: "k8s.io/ingress-nginx"
      service:
          # Disable the external LB
        external:
          enabled: false
        internal:
          enabled: true
          annotations:
            # Create internal ELB
            service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
            service.beta.kubernetes.io/aws-load-balancer-type: external
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
            service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0ee18f52b4f2a75f4, subnet-0880cc3d78939fe04, subnet-03307a01716b9ba07
            service.beta.kubernetes.io/load-balancer-source-ranges: 10.0.0.0/8