apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dummy-go
resources:
  - namespace.yaml
  - image.yaml
  - deployment.yaml
  - image-repository.yaml
  - service.yaml
  - ingress.yaml