apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app-img
        image: private-docker-registry.local-services.svc.cluster.local:30050/java-app-img:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: image-registry-credentials
