---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJwcml2YXRlLWRvY2tlci1yZWdpc3RyeS5sb2NhbC1zZXJ2aWNlcy5zdmMuY2x1c3Rlci5sb2NhbDozMDA1MCI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3N3b3JkIiwiYXV0aCI6ImRYTmxjanB3WVhOemQyOXlaQT09In19fQ==
kind: Secret
metadata:
  name: image-registry-credentials
  namespace: java-app
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-service-account
  namespace: java-app
secrets:
  - name: image-registry-credentials
imagePullSecrets:
  - name: image-registry-credentials
---
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: java-app-img
  namespace: java-app
spec:
  tag: private-docker-registry.local-services.svc.cluster.local:30050/java-app-img
  serviceAccountName: kpack-service-account
  builder:
    name: image-builder
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/spring-projects/spring-petclinic
      revision: 82cb521d636b282340378d80a6307a08e3d4a4c4