kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: java-app
  namespace: java-app
spec:
  rules:
    - host: java-app.staging
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: java-app-service
                port:
                  number: 8080