-- Control-plane schema v1 (RFC-0033 phase 1): the workspace, the people it
-- has seen, teams and grants. Identifiers are UUID strings generated by the
-- server so the same rows can be exported and imported across installs.

CREATE TABLE workspaces (
    id         TEXT PRIMARY KEY,
    slug       TEXT NOT NULL UNIQUE,
    name       TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE identities (
    id            TEXT PRIMARY KEY,
    workspace_id  TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    realm         TEXT NOT NULL DEFAULT 'workspace',
    email         TEXT NOT NULL,
    name          TEXT NOT NULL DEFAULT '',
    provider      TEXT NOT NULL DEFAULT '',
    groups        JSONB NOT NULL DEFAULT '[]',
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (workspace_id, realm, email)
);

CREATE TABLE teams (
    id            TEXT PRIMARY KEY,
    workspace_id  TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    name          TEXT NOT NULL,
    description   TEXT NOT NULL DEFAULT '',
    members       JSONB NOT NULL DEFAULT '[]',
    groups        JSONB NOT NULL DEFAULT '[]',
    platform_role TEXT NOT NULL DEFAULT '',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (workspace_id, name)
);

CREATE TABLE grants (
    id           TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    project      TEXT NOT NULL,
    role         TEXT NOT NULL,
    user_email   TEXT NOT NULL DEFAULT '',
    team_id      TEXT REFERENCES teams(id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK ((user_email = '') <> (team_id IS NULL))
);

-- One grant per (project, role, subject); NULL team ids must compare equal,
-- which a plain UNIQUE constraint would not do.
CREATE UNIQUE INDEX grants_unique ON grants (workspace_id, project, role, user_email, COALESCE(team_id, ''));
CREATE INDEX grants_project ON grants (workspace_id, project);
