version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached
      - ~/.kube:/home/vscode/.kube:ro

    extra_hosts:
      - "kubernetes.default.svc.cluster.local:host-gateway"

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity