apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-service-account
  namespace: management
secrets:
- name: image-registry-credentials
imagePullSecrets:
- name: image-registry-credentials
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: default
  namespace: management
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/java
  - image: gcr.io/paketo-buildpacks/nodejs
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: base
  namespace: management
spec:
  id: "io.buildpacks.stacks.jammy"
  buildImage:
    image: "paketobuildpacks/build-jammy-base"
  runImage:
    image: "paketobuildpacks/run-jammy-base"
---
apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: image-builder
  namespace: management
spec:
  serviceAccountName: kpack-service-account
  tag: localregistry-docker-registry.management.svc.cluster.local:30050/builder
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/nodejs
