apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shpyrd-system
labels:
  - pairs:
      app.kubernetes.io/part-of: shpyrd
resources:
  - crds/shpyrd.io_apps.yaml
  - crds/shpyrd.io_volumes.yaml
  - crds/shpyrd.io_teams.yaml
  - crds/shpyrd.io_projectmembers.yaml
  - rbac.yaml
  - storage.yaml
  - server.yaml
  - ingress.yaml
