apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logs-system
labels:
  - pairs:
      app.kubernetes.io/part-of: shpyrd
      app.kubernetes.io/name: vector
resources:
  - namespace.yaml
  - rbac.yaml
  - config.yaml
  - daemonset.yaml
