---
apiVersion: v1
kind: Namespace
metadata:
  name: local-infra
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: twun
  namespace: local-services
spec:
  interval: 24h
  url: https://helm.twun.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: private
  namespace: local-services
spec:
  interval: 30m
  chart:
    spec:
      chart: docker-registry
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: twun
        namespace: local-services
      interval: 12h
  values:
    service:
      type: "NodePort"
      nodePort: 30050
      port: 30050
    persistence:
      enabled: true
      deleteEnabled: true
    secrets:
      htpasswd: "user:$2y$05$Ue5dboOfmqk6Say31Sin9uVbHWTl8J1Sgq9QyAEmFQRnq1TPfP1n2"
